[project]
name = "anthias"
version = "0.20.4"
description = "The world's most popular open source digital signage project."
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev-host = [
    "ruff==0.14.10",
]
docker-image-builder = [
    "click==8.1.7",
    "jinja2==3.1.6",
    "pygit2==1.19.1",
    "requests==2.32.5",
    "python-on-whales==0.79.0",
]
