---
- name: Check screenly.conf
  command: cat /home/pi/.screenly/screenly.conf
  register: config
  tags:
    - enable-ssl

- set_fact: no_use_ssl_parameter="{{config.stdout.find('use_ssl') == -1}}"
  tags:
    - enable-ssl

- name: Installs Nginx
  apt:
    name: nginx-light
    state: present
    update_cache: yes
  tags:
    - enable-ssl

- name: Cleans up default config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  tags:
    - enable-ssl

- name: Installs nginx config
  copy:
    src: nginx.conf
    dest:  /etc/nginx/sites-enabled/screenly.conf
    mode: 644
    owner: root
    group: root
  notify:
    - restart-nginx
  tags:
    - enable-ssl

- name: Installs self-signed certificates
  copy:
    src: "{{ item }}"
    dest: "/etc/ssl/{{ item }}"
    mode: 0600
    owner: root
    group: root
    force: no
  with_items:
    - screenly.crt
    - screenly.key
  tags:
    - enable-ssl

- name: Turn on the ssl mode
  lineinfile:
    dest: /home/pi/.screenly/screenly.conf
    insertafter: '^.*database.*'
    regexp: '^.*database.*;'
    line: 'use_ssl = True'
  tags:
    - enable-ssl
  when: no_use_ssl_parameter

- name: Turns on the ssl mode
  replace:
    replace: 'use_ssl = True'
    regexp: '^.*use_ssl.*'
    dest: /home/pi/.screenly/screenly.conf
  tags:
    - enable-ssl
  when: not no_use_ssl_parameter

- name: Modifies screenly-web service to only listen on localhost
  lineinfile:
    regexp: '^.*LISTEN.*'
    state: absent
    dest: /etc/systemd/system/screenly-web.service
  notify:
    - reload systemctl
    - restart-screenly-websocket_server_layer
    - restart-screenly-server
  tags:
    - enable-ssl
