- name: Install Screenly
  hosts: all
  user: pi
  become: yes
  vars:
    manage_network: "{{ lookup('env', 'MANAGE_NETWORK') }}"
    docker_tag: "{{ lookup('env', 'DOCKER_TAG') }}"
    device_type: "{{ lookup('env', 'DEVICE_TYPE') }}"

  roles:
    - system
    - screenly
    - network
    - splashscreen
    - tools
