---

# If Jessie
- name: Installs dependencies (Jessie)
  ansible.builtin.apt:
    name: fbi
  when: ansible_distribution_major_version|int <= 7

- name: Copies in splash screen
  ansible.builtin.copy:
    src: splashscreen.png
    dest: /etc/splashscreen.png
  when: ansible_distribution_major_version|int <= 7

- name: Copies in rc script
  ansible.builtin.copy:
    src: asplashscreen
    dest: /etc/init.d/asplashscreen
    mode: 0755
  when: ansible_distribution_major_version|int <= 7

- name: Enables asplashscreen
  ansible.builtin.command: update-rc.d asplashscreen defaults
  args:
    creates: /etc/rcS.d/S01asplashscreen
  when: ansible_distribution_major_version|int <= 7

# If not Jessie
- name: Remove older versions
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /etc/splashscreen.jpg
    - /etc/init.d/asplashscreen
  when: ansible_distribution_major_version|int > 7

- name: Disable asplashscreen
  ansible.builtin.command: update-rc.d asplashscreen remove
  when: ansible_distribution_major_version|int > 7

- name: Installs dependencies (not Jessie)
  ansible.builtin.apt:
    name: plymouth
  when: ansible_distribution_major_version|int > 7

- name: Copies plymouth theme
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/share/plymouth/themes/screenly/
  with_items:
    - screenly.plymouth
    - screenly.script
    - splashscreen.png
  when: ansible_distribution_major_version|int > 7

- name: Set splashscreen
  ansible.builtin.command: plymouth-set-default-theme -R screenly
  when: ansible_distribution_major_version|int > 7

- name: Set plymouthd.default
  ansible.builtin.copy:
    src: plymouthd.default
    dest: /usr/share/plymouth/plymouthd.defaults
  when: ansible_distribution_major_version|int > 7
  
- name: Copy to plymouthd.conf
  ansible.builtin.copy:
    src: plymouthd.default
    dest: /etc/plymouth/plymouthd.conf
  when: ansible_distribution_major_version|int > 7
  
