screenly_systemd_units:
  - udev-restart.service
  - screenly-host-agent.service

deprecated_screenly_systemd_units:
  - screenly-celery.service
  - screenly-web.service
  - screenly-websocket_server_layer.service
  - screenly-viewer.service
  - X.service
  - matchbox.service
  - wifi-connect.service
